services:
  - type: web
    name: drinks-backend
    runtime: docker
    plan: free
    envVars:
      - key: "DATABASE_URL"
        value: ""
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        value: your_password
